# Generated by Django 4.2.19 on 2025-03-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dataentry',
            table='data_entry',
        ),
    ]
